### ISSUE TITLE
Edge in master branche fail

### ISSUE THREAD

**Issue by Muskos** [serbanghita/Mobile-Detect#552] opened 2016-05-16 11:03 UTC
I take MobileDetect from here:
https://github.com/serbanghita/Mobile-Detect/blob/master/Mobile_Detect.php
Test on desktop Edge - $detect->isMobile() returned 1

Plz check this. I take release version - all right.
thx for your work

**Comment by serbanghita** [comment] 2016-05-16 11:11
I'll check, is because I merged a commit without tests :(
Thanks for catching this!

**Comment by Muskos** [comment] 2016-05-16 11:14
np 
Thanks for you)

**Comment by javierenciso** [comment] 2016-06-21 14:34
Hi there...
is this solved?
/thanx
/j

**Comment by serbanghita** [comment] 2016-11-11 15:33
This should not reproduce anymore. I've tested from my Edge.

**Closed by serbanghita** 2016-11-11 15:33 UTC
Labels: bug
